import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:study_app/models/content_pack.dart';

/// Validates the bundled production content pack.
///
/// The pack is generated by `tool/build_content_pack.py` from the authoring
/// sources under `tool/content/`. This test guards the shipped artifact so a
/// schema or provenance regression cannot reach the binary silently.
void main() {
  late ContentPack pack;

  setUpAll(() {
    final file = File('assets/content-pack.json');
    expect(file.existsSync(), isTrue,
        reason: 'assets/content-pack.json must be generated before testing');
    pack = ContentPack.parse(file.readAsStringSync());
  });

  test('production pack parses and passes structural validation', () {
    final errors = ContentPackValidator(pack).validate();
    expect(errors, isEmpty, reason: errors.join('\n'));
  });

  test('production pack ships the three launch courses', () {
    final courses = pack.questions.map((q) => q.courseId).toSet();
    expect(courses, containsAll(['az-900', 'dp-900', 'ai-901']));
  });

  test('every production question has a permitted rights basis', () {
    const permitted = [
      'original-human',
      'original-human-ai-assisted',
      'licensed-cc-by-4.0',
      'licensed-commercial',
      'public-domain',
    ];
    for (final q in pack.questions) {
      expect(permitted, contains(q.rightsBasis),
          reason: '${q.id} has rightsBasis "${q.rightsBasis}"');
    }
  });

  test('AZ-900 replaces all 133 legacy slots plus the 7 gap topics', () {
    final az = pack.questions.where((q) => q.courseId == 'az-900').toList();
    expect(az.length, greaterThanOrEqualTo(140));
  });

  test('question ids are unique across the pack', () {
    final ids = pack.questions.map((q) => q.id).toList();
    expect(ids.toSet().length, ids.length);
  });
}
