import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:study_app/models/content_pack.dart';

/// Validates the bundled production content pack.
///
/// The pack is generated by `tool/build_content_pack.py` from the authoring
/// sources under `tool/content/`. This test guards the shipped artifact so a
/// schema or provenance regression cannot reach the binary silently.
void main() {
  late ContentPack pack;

  setUpAll(() {
    final file = File('assets/content-pack.json');
    expect(file.existsSync(), isTrue,
        reason: 'assets/content-pack.json must be generated before testing');
    pack = ContentPack.parse(file.readAsStringSync());
  });

  test('production pack parses and passes structural validation', () {
    final errors = ContentPackValidator(pack).validate();
    expect(errors, isEmpty, reason: errors.join('\n'));
  });

  test('production pack ships the three launch courses', () {
    final courses = pack.questions.map((q) => q.courseId).toSet();
    expect(courses, containsAll(['az-900', 'dp-900', 'ai-901']));
  });

  test('every production question has a permitted rights basis', () {
    const permitted = [
      'original-human',
      'original-human-ai-assisted',
      'licensed-cc-by-4.0',
      'licensed-commercial',
      'public-domain',
    ];
    for (final q in pack.questions) {
      expect(permitted, contains(q.rightsBasis),
          reason: '${q.id} has rightsBasis "${q.rightsBasis}"');
    }
  });

  test('course item counts match the documented coverage', () {
    final counts = <String, int>{};
    for (final q in pack.questions) {
      counts[q.courseId] = (counts[q.courseId] ?? 0) + 1;
    }
    expect(counts, {'az-900': 146, 'dp-900': 57, 'ai-901': 47});
  });

  test('AZ-900 ships every slot except the recorded duplicates', () {
    final az = pack.questions.where((q) => q.courseId == 'az-900').toList();
    // Ids run 001..156. Dropped slots are duplicate topics whose subject is
    // retained elsewhere, or weighting-pad items removed for same-fact
    // duplication; see docs/content-provenance.md.
    final dropped = {
      'az-900-019',
      'az-900-056',
      'az-900-061',
      'az-900-079',
      'az-900-090',
      'az-900-103',
      'az-900-109',
      'az-900-141',
      'az-900-143',
      'az-900-152',
    };
    final expected = {
      for (var n = 1; n <= 156; n++) 'az-900-${n.toString().padLeft(3, '0')}',
    }..removeAll(dropped);

    expect(az.length, 146);
    expect(az.map((q) => q.id).toSet(), expected);
  });

  test('question ids are unique across the pack', () {
    final ids = pack.questions.map((q) => q.id).toList();
    expect(ids.toSet().length, ids.length);
  });
}
